# NAME : SUJANA KOLA
# Reg No : 20MIS0171

In [4]:
name='Sujana'
age=19
print(name)
print(age)

Sujana
19


In [6]:
X= "Datascience is used to extract meaningful insights"
split_str=X.split()
print(split_str)

['Datascience', 'is', 'used', 'to', 'extract', 'meaningful', 'insights']


In [16]:
def multiplication(a,b):
    x=a*b
    print('The multiplication of',a,'and',b ,'is',x)
a=int(input("Enter the first number:"))
b=int(input("Enter the second number:"))
multiplication(a,b)

Enter the first number:4
Enter the second number:6
The multiplication of 4 and 6 is 24


In [21]:
d={'Hyderabad':'Telangana','Mumbai':'Maharashtra','Bangalore':'Karnataka','Itanagar':'Arunachal Pradesh','Kolkata':'West Bengal'}
d.keys()

dict_keys(['Hyderabad', 'Mumbai', 'Bangalore', 'Itanagar', 'Kolkata'])

In [22]:
d={'Hyderabad':'Telangana','Mumbai':'Maharashtra','Bangalore':'Karnataka','Itanagar':'Arunachal Pradesh','Kolkata':'West Bengal'}
d.values()

dict_values(['Telangana', 'Maharashtra', 'Karnataka', 'Arunachal Pradesh', 'West Bengal'])

In [32]:
import numpy as np
y=np.arange(1001)
print(y)

[   0    1    2 ...  998  999 1000]


In [38]:
var=np.eye((4))
var

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [43]:
m=np.arange(1,10).reshape(1,3,3)
m

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [44]:
import pandas as pd
array1 = pd.DataFrame([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
array2 = pd.DataFrame([[10, 11, 12], [13, 14, 15], [16, 17, 18]])
result = array1 + array2
print(result)

    0   1   2
0  11  13  15
1  17  19  21
2  23  25  27


In [50]:
import pandas as pd

start_date = pd.to_datetime('2023-02-01')
end_date = pd.to_datetime('2023-03-01')

date_series = pd.date_range(start=start_date, end=end_date)

print(date_series)

DatetimeIndex(['2023-02-01', '2023-02-02', '2023-02-03', '2023-02-04',
               '2023-02-05', '2023-02-06', '2023-02-07', '2023-02-08',
               '2023-02-09', '2023-02-10', '2023-02-11', '2023-02-12',
               '2023-02-13', '2023-02-14', '2023-02-15', '2023-02-16',
               '2023-02-17', '2023-02-18', '2023-02-19', '2023-02-20',
               '2023-02-21', '2023-02-22', '2023-02-23', '2023-02-24',
               '2023-02-25', '2023-02-26', '2023-02-27', '2023-02-28',
               '2023-03-01'],
              dtype='datetime64[ns]', freq='D')


In [51]:
import pandas as pd
dictionary = {'Brand': ['Maruti', 'Renault', 'Hyundai'], 'Sales': [250, 200, 240]}
df = pd.DataFrame(dictionary)
print(df)

     Brand  Sales
0   Maruti    250
1  Renault    200
2  Hyundai    240
